/**
 * RapidCargo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RefTypeDto } from './refType';


export interface GoodsDto { 
    refType: RefTypeDto;
    /**
     * Si refType = AWB, alors refCode doit être exactement 11 chiffres (contrôle dynamique côté serveur). 
     */
    refCode: string;
    /**
     * Quantité mouvementée (doit être ≤ totalQuantity, règle métier côté serveur)
     */
    quantity: number;
    /**
     * Poids mouvementé (doit être ≤ totalWeight, règle métier côté serveur)
     */
    weight: number;
    description?: string;
    /**
     * Quantité totale contractuelle/attendue (plafond)
     */
    totalQuantity: number;
    /**
     * Poids total contractuel/attendu (plafond)
     */
    totalWeight: number;
}



