/**
 * RapidCargo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomsDocumentDto } from './customsDocument';
import { MovementTypeDto } from './movementType';
import { GoodsDto } from './goods';
import { WarehouseDto } from './warehouse';


export interface MovementDto { 
    movementType: MovementTypeDto;
    movementTime: string;
    createdBy: string;
    declaredIn: WarehouseDto;
    fromWarehouse?: WarehouseDto;
    toWarehouse?: WarehouseDto;
    goods: GoodsDto;
    customsStatus: string;
    customsDocument?: CustomsDocumentDto;
}



