/**
 * RapidCargo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomsDocumentDto } from './customsDocument';
import { MovementTypeDto } from './movementType';
import { GoodsDto } from './goods';
import { WarehouseDto } from './warehouse';


/**
 * Requête de création d\'un mouvement. Règles métier (côté serveur) : - quantity/weight ≤ totalQuantity/totalWeight - si refType = AWB alors refCode = exactement 11 chiffres - OUT ≤ disponible (Σ IN – Σ OUT) 
 */
export interface MovementCreateRequestDto { 
    movementType: MovementTypeDto;
    movementTime: string;
    createdBy: string;
    declaredIn: WarehouseDto;
    fromWarehouse?: WarehouseDto;
    toWarehouse?: WarehouseDto;
    goods: GoodsDto;
    /**
     * Statut douanier (code 1 lettre)
     */
    customsStatus: string;
    customsDocument?: CustomsDocumentDto;
}



