/**
 * RapidCargo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * RFC 7807 Problem Details
 */
export interface ProblemDto { 
  [key: string]: any | any;


    type: string;
    title: string;
    status: number;
    detail?: string;
    instance?: string;
}

