/**
 * RapidCargo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RefTypeDto } from './refType';


export interface ReferenceAvailabilityResponseDto { 
    refType: RefTypeDto;
    refCode: string;
    totalQuantity: number;
    totalWeight: number;
    sumInQuantity: number;
    sumOutQuantity: number;
    availableQuantity: number;
    availableWeight: number;
}



