/**
 * RapidCargo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type de référence marchandise
 */
export enum RefTypeDto {

    Awb = 'AWB',

    Other = 'OTHER'
}

