version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: tms-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cargo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: tms-mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # UI web

  sb-admin:
    image: openjdk:21-jdk
    container_name: tms-sb-admin
    working_dir: /app
    volumes:
      - ../tms-sb-admin/target/tms-sb-admin-0.0.1-SNAPSHOT.jar:/app/app.jar:ro
    command: ["java", "-jar", "app.jar"]
    ports:
      - "9000:9000"
    restart: always

volumes:
  pgdata:
