sonar.projectKey=cargo-tms-contracts-api
sonar.projectName=Contracts API
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.language=java
sonar.sourceEncoding=UTF-8
